# Site settings
title: Stephen Houser
email: stephenhouser@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of thoughts, ideas, and work making things in
  Software Development, Woodworking, Amatuer Radio, Electronics,
  and more.
baseurl: "" # the subpath of your site, e.g. /blog/
xurl: "http://blog.stephenhouser.com" # the base hostname & protocol for your site
timezone: America/New_York

twitter_username: stephenhouser
github_username: stephenhouser
linkedin_username: stephenahouser
facebook_username: stephenhouser
aboutme_username: stephenhouser
googleplus_username: stephenhouser
stackoverflow_username: stephenhouser
flickr_username: stephenhouser
youtube_username: stephenhouser
qrz_username: n1sh
arrl_username: stephen-houser
pintrest_username: stephen_houser
# tumblr_username:
# instagram_username:

# Build settings
xmarkdown: kramdown
markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

excerpt_separator: <!-- more -->
paginate: 7


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Stephen Houser"
