#
# Stephen Houser's personal website, blog, and portfolio
#
# Basic Site settings
title: Stephen Houser
email: stephenhouser@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of thoughts, ideas, and work making things in
  Software Development, Woodworking, Amatuer Radio, Electronics,
  and more.

# Deployment Settings
#
# DEFAULT GitHub/Dropbox Configuration
# * Base site on GitHub -- http://stephenhouser.github.io

# Google Analytics Configuration
# DEFAULT: http://stephenhouser.com
#google_analytics: UA-2571363-2

# The place I keep the source
repository: stephenhouser/stephenhouser.githib.io

baseurl:    ""        # the subpath of the site, e.g. /~houser
assetsurl:  "/assets" # images, icons, and small assets used in posts
filesurl:   "http://media.stephenhouser.com" # Where the larger "files" go

# Site Build settings
timezone:   America/New_York

permalink:  /blog/:year/:month-:day-:title.html
paginate:   7
paginate_path: /blog/pager/page-:num/

# When clobbering the destination, don't muck with these
keep_files: ['CampusCrush', 'files']
exclude:    ['makefile', 'files', 'Gemfile*', 'CNAME']
include:    []
safe:       true
future:     false

# Code highlighting
highlight:  pygments

# Generate the sitemap.xml file
plugins: 
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-gist

# Whitelist plugins for working in safe mode locally
whitelist: 
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-gist

# Default settings for posts and the like...
defaults:
  - scope:
      path: "" # empty = all files
      type: "posts"      
    values:
      layout: "post"
      comments: true
  - scope:
      path: "" # empty = all files
      type: "project"      
    values:
      layout: "project"
      comments: false
