#
# Stephen Houser's personal website, blog, and portfolio
#
# Basic Site settings
title: Stephen Houser
email: stephenhouser@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of thoughts, ideas, and work making things in
  Software Development, Woodworking, Amatuer Radio, Electronics,
  and more.

# Deployment Settings
#
# DEFAULT GitHub/Dropbox Configuration
# * Base site on GitHub -- http://stephenhouser.github.io
# * Files served from Dropbox -- https://dl.dropboxusercontent.com/u/9832808
# May get overriden by other --config's when building

# Google Analytics Configuration
# DEFAULT: http://stephenhouser.com
google_analytics: UA-2571363-2

#
# I don't use "url" anyhere, kept here for reference.
# The base hostname & protocol for your site
#url: "http://stephenhouser.com"

repository: stephenhouser/stephenhouser.githib.io

baseurl:    "" # the subpath of your site, e.g. /blog/
assetsurl:  /assets
# Larger files are located in DropBox's Public directory
# 2016/12/16: Dropbox is dropping public directories.
#filesurl:   https://dl.dropboxusercontent.com/u/9832808
# These are other locations where files might go...
#filesurl:   "/files"       # files are in a local directory
filesurl:   "http://media.stephenhouser.com" # Amazon S3

# Site Build settings
timezone:   America/New_York
permalink:  /:categories/:year-:month-:day-:title.html
#excerpt_separator: <!-- more --> # default is \n\n
paginate:   7

# When clobbering the destination, don't muck with these
keep_files: ['CampusCrush', 'files']
exclude:    ['makefile', 'files', 'Gemfile*', 'CNAME']
include:    []
safe:       true
future:     false

# Code highlighting
highlight:  pygments

# Generate the sitemap.xml file
gems: 
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-gist

# Whitelist plugins for working in safe mode locally
whitelist: 
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-gist

# Default settings for posts and the like...
defaults:
  -
    scope:
      path: "" # empty = all files
      type: "posts"      
    values:
      layout: "post"
      author: "Stephen Houser"
      comments: true

