# Site settings
title: Stephen Houser
email: stephenhouser@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of thoughts, ideas, and work making things in
  Software Development, Woodworking, Amatuer Radio, Electronics,
  and more.

#url: "http://blog.stephenhouser.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
assetsurl: /assets
filesurl: http://media.usm.maine.edu/~houser
timezone: America/New_York

permalink: /:categories/:year-:month-:day-:title.html

# Build settings
highlight: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

#excerpt_separator: <!-- more --> # default is \n\n
paginate: 7

gems:
  - jekyll-sitemap

defaults:
  -
    # Make default layout for posts be post
    scope:
      path: "" # empty = all files
      type: "posts"
    values:
      layout: "post"
      author: "Stephen Houser"

# When clobbering the destination, don't muck with these
keep_files: ['CampusCrush', 'files']
exclude: ['makefile', 'files', 'Gemfile*']
include: []
safe: true
