# Site settings
title: Stephen Houser
email: stephenhouser@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of thoughts, ideas, and work making things in
  Software Development, Woodworking, Amatuer Radio, Electronics,
  and more.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://blog.stephenhouser.com" # the base hostname & protocol for your site
timezone: America/New_York

# Build settings
highlight: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

#excerpt_separator: <!-- more -->
paginate: 7

gems:
  - jekyll-sitemap

defaults:
  -
    # Make default layout for posts be post
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Stephen Houser"
