#
# Stephen Houser's personal website, blog, and portfolio
#
# Basic Site settings
title: Stephen Houser
email: stephenhouser@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of thoughts, ideas, and work making things in
  Software Development, Woodworking, Amatuer Radio, Electronics,
  and more.

# Deployment Settings
#
# DEFAULT GitHub/Dropbox Configuration
# * Base site on GitHub -- http://stephenhouser.github.io
# * Files served from Dropbox -- https://dl.dropboxusercontent.com/u/9832808
# May get overriden by other --config's when building

# Google Analytics Configuration
# DEFAULT: http://stephenhouser.com
google_analytics: UA-2571363-2

#
# I don't use "url" anyhere, kept here for reference.
# The base hostname & protocol for your site
#url: "http://stephenhouser.com"
baseurl:    "" # the subpath of your site, e.g. /blog/
assetsurl:  /assets
#filesurl:   /files
#filesurl:   https://dl.dropboxusercontent.com/u/9832808/stephenhouser.com-files
filesurl:   https://dl.dropboxusercontent.com/u/9832808
#filesurl:   http://media.stephenhouser.com

# Site Build settings
timezone:   America/New_York
permalink:  /:categories/:year-:month-:day-:title.html
#excerpt_separator: <!-- more --> # default is \n\n
paginate:   7

# When clobbering the destination, don't muck with these
keep_files: ['CampusCrush', 'files']
exclude:    ['makefile', 'files', 'Gemfile*', 'CNAME']
include:    []
safe:       true

# Code highlighting
highlight:  pygments
markdown:   redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Generate the sitemap.xml file
gems:
  - jekyll-sitemap

# Default settings for posts and the like...
defaults:
  -
    scope:
      path: "" # empty = all files
      type: "posts"
    values:
      layout: "post"
      author: "Stephen Houser"

